### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by yoshkin**
Beacuse "begin_page_ext" method is waiting for "pt" - we need to convert to "pt", not to "mm"

### CODE REVIEW

**Comment by fabricecw** [comment]
I'll check it out later this day, but it seems pretty obvious. 
Please apply the StyleCI fixes. Thanks!

**Comment by yoshkin** [comment]
Did you test my case ?

**Comment by yoshkin** [comment]
Founded another bug (with image positions)

**Review by fabricecw — CHANGES_REQUESTED** [review]
This changes are incorrect. The class variables `xPos` and `yPos` are always stored in `pt`, so it has to take `pt` as the unit. But as before, it has to be the `calculateToPt` method instead of `calculateToMm`. Could you fix that? Also on line 325, 361, 362 and 363. Thanks!

**Comment by yoshkin** [comment]
Also updated default "fitOptions"  to "pt"

**Pull request merged**
